language: node_js
node_js:
  - 10
env:
  global:
    - RELEASE_VERSION=1.1.0.0
    - DEFAULT_LOCALHOST=https://localhost:3000
    - PROD_URL=https://dfslh8qg8d862.cloudfront.net/${RELEASE_VERSION}
    - UAT_URL=https://dfslh8qg8d862.cloudfront.net/uat/${RELEASE_VERSION}
cache:
  directories:
  - node_modules
install:
- npm install
before_script: chmod 0777 ./node_modules/.bin/jest
script:
- npm run test --coverage
- npm run build
before_deploy:
- rm -rf node_modules
jobs:
  include:    
    - stage: deploy-develop
      if: branch = develop
      name: "Deploy to develop S3"
      script: skip
      deploy:
        provider: script
        script: bash uat_scripts.sh develop
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: $PROD_S3
        skip_cleanup: true
        on:
          branch: develop
          condition: $TRAVIS_BRANCH = develop

    - stage: deploy-prod
      if: branch = master
      name: "Deploy to production S3"
      script: skip
      deploy:
        provider: script
        script: bash prod_scripts.sh master
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: $PROD_S3
        skip_cleanup: true
        on:
          branch: master
          condition: $TRAVIS_BRANCH = master
